### PR TITLE
adding hollow circle and solid circle pattern hacktoberfest 2024

### PR DESCRIPTION
**Pull request by Saiharitha3**
Hi @aviraw  "I am enhancing the repository by adding new patterns for both hollow and solid circles, contributing to a more diverse collection of geometric shapes."

### CODE REVIEW

**Review by aviraw — CHANGES_REQUESTED** [review]
Please don't add the license.

**Comment by aviraw** [comment]
There are some conflicts. Please resolve.

**Comment by Saiharitha3** [comment]
> Please don't add the license.

okay sure i will remove license file

**Comment by Saiharitha3** [comment]
please review it now

**Comment by Saiharitha3** [comment]
@aviraw please add hacktoberfest label

**Pull request merged**
