### PR TITLE
Create Patterns-in-Java

### PR DESCRIPTION
**Pull request by Student-PrangyaParamita**
This file contains butterfly pattern, number pyramid pattern and one more pattern

### CODE REVIEW

**Comment by Student-PrangyaParamita** [comment]
patterns print using java

**Review by Student-PrangyaParamita — COMMENTED** [review]
import the butterfly pattern code

**Comment by Student-PrangyaParamita** [comment]
Butterfly pattern in java

**Review by aviraw — CHANGES_REQUESTED** [review]
Please add your name and file name. See contributing.md for more details.

**Pull request merged**
