### PR TITLE
Create PerfectSquarePattern.java

### PR DESCRIPTION
**Pull request by KSVeerendernath**
Hi @aviraw ,

I hope you are doing well!

I have created a new pattern that generates square patterns as described below:

**Add PerfectSquarePattern.java to generate a grid of perfect squares:**

- Implemented functionality to create a pattern of perfect squares.
- Added user input for specifying the number of rows and columns.
- Implemented alternate shading for the generated squares.

**Sample output:**

image

Please help approve my PR for Hacktoberfest.

Let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by aviraw** [comment]
See contributing.md add your name and file name.

**Comment by KSVeerendernath** [comment]
Hi @aviraw , Thanks for your response!! As instructed I have made changes and added my name on .md file please find new pr #43 . Thanks!!

**Comment by KSVeerendernath** [comment]
Hi @aviraw , Could you please help to approve this PR, please let me know if you need any other additional details thanks!!

**Comment by KSVeerendernath** [comment]
Hi @aviraw, Thanks for approving my PR, I appreciate your time and efforts, I request you to please add Hactoberfest 2024 so that this will be considered for the fest. Thanks!!

**Pull request merged**
